
package com.xlj.jaxws.webservice.test;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductWS", targetNamespace = "http://webservice.jaxws.xlj.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductWS {


    /**
     * 
     * @return
     *     returns java.util.List<com.xlj.jaxws.webservice.test.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers",
            targetNamespace = "http://webservice.jaxws.xlj.com/",
            className = "com.xlj.jaxws.webservice.test.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse",
            targetNamespace = "http://webservice.jaxws.xlj.com/",
            className = "com.xlj.jaxws.webservice.test.GetAllUsersResponse")
    @Action(input = "http://webservice.jaxws.xlj.com/ProductWS/getAllUsersRequest",
            output = "http://webservice.jaxws.xlj.com/ProductWS/getAllUsersResponse")
    public List<User> getAllUsers();

}
